# The class to initialise, and init parameters
_initialise_class:
    class: HardwareRepository.HardwareObjects.Beamline.BeamlineSubclass
    # Further key-value pairs here will be passed to the class init
    mode: devel

# objects
#
# Eventually all objects should use the yaml config system like Beamline,
# but for now we can leave them as xml
#
# NBNB some objects that do not currently have their own config files
# would need those added (e.g. the centring methods)
#
_objects:
    # The values are the file paths to the configuration file for the
    # object, relative to the configuration file path(s)
    #
    # Hardware:
    machine_info: mach-info.xml
    transmission: attenuators.xml
    energy: energy.xml
    flux: flux.xml
    beam: beam-info.xml
    hutch_interlock: door-interlock.xml
    safety_shutter: safshut.xml
    fast_shutter: fast-shut.xml
    diffractometer: mini-diff.xml
    detector: eh1/detector.xml
    resolution: eh1/resolution.xml
    sample_changer: sc-generic.xml
    session: session.xml
    lims: dbconnection.xml
    graphics: graphics.xml
    queue_manager: queue.xml
    queue_model: queue_model.xml
    # Procedures:
    collect: mxcollect.xml
    xrf_spectrum: xrf-spectrum.xml
    energy_scan: energyscan.xml
    imaging: xray-imaging.xml
    gphl_workflow: gphl-workflow.yml
    gphl_connection: gphl-setup.yml
    # Centring:
    n_click_centring: three-click-centring.xml
    move_to_beam: move-to-beam.xml
    # optical_centring: # Skipped - optional
    # x_ray_centring: # Skipped - optional
    # Analysis:
    online_processing: auto-processing.xml
    offline_processing: parallel-processing.xml
    edna_characterisation: data-analysis.xml
    # Subclass-specific objects:
    beam_definer: eh1/beamFocusing.xml
    # beam_realign: # Skipped - optional
    # NB this one does not yet exist, but should be written:
    default_characterisation_parameters: default_characterisation_parameters.xml
# Non-object attributes:
advanced_methods:
  - MeshScan
  - XrayCentering
tunable_wavelength: true
disable_num_passes: false

